// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';


const SUPABASE_URL = "https://glgjavpwdvyijjzkwlwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdsZ2phdnB3ZHZ5aWpqemt3bHdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MDgzODIsImV4cCI6MjA3Mjk4NDM4Mn0.IudLcci1wT7ejzKKeB9DcXX1jPW98R8o_K3nu54R3nQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});